stages:
  - build
  - deploy

build_project:
  stage: build
  image: node:20
  script:
    - npm install
    - npm run build

deploy_project:
  stage: deploy
  image: node:20
  script:
    - |
      HTTP_STATUS=$(curl -s -o response.txt -w "%{http_code}" -X POST "https://ikgcartoapps.ethz.ch/deploy/project" \
      -H "Content-Type: application/json" \
      -H "x-project-secret: ${CI_PROJECT_SECRET}" \
      -d "{\"repository\": \"${CI_PROJECT_NAME}\", \"namespace\": \"${CI_PROJECT_NAMESPACE}\"}")

      if [ -f response.txt ]; then
        cat response.txt
      else
        echo "No response received."
      fi

      if [ "$HTTP_STATUS" -ne 200 ]; then
        exit 1
      fi
  only:
    - main
  when: manual
  allow_failure: false
